services:
  api:
    image: api
    ports:
      - "8080:8080"
    networks:
      - publicNetwork
    depends_on:
      - database 
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: clientesdb
    networks:
      - publicNetwork

networks:
  publicNetwork:

    